version: "3.8"

services:
  console:
    build:
      context: .
      dockerfile: docker/console.Dockerfile
    image: tabletoplabs/console:latest
    ports:
      - 3001:3000

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    image: tabletoplabs/worker:latest
    ports:
      - 3002:3000

  agent:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    image: tabletoplabs/agent:latest
    ports:
      - 3003:3000

  explore:
    build:
      context: .
      dockerfile: docker/explore.Dockerfile
    image: tabletoplabs/explore:latest
    ports:
      - 3004:3000

  db2:
    image: icr.io/db2_community/db2
    platform: linux/amd64
    privileged: true
    ports:
      - "50000:50000"
    environment:
      - LICENSE=${DB2_LICENSE:-accept}
      - DB2INST1_PASSWORD=${DB2_DBINST1_PASSWORD:-password}
      - DBNAME=${DB2_DBNAME:-duckdb}
      - DB2INSTANCE=${DB2_DB2INSTANCE:-db2inst1}
      - BLU=${DB2_BLU:-false}
      - ENABLE_ORACLE_COMPATIBILITY=${DB2_ENABLE_ORACLE_COMPATIBILITY:-false}
      - UPDATEAVAIL=${DB2_UPDATEAVAIL:-NO}
      - TO_CREATE_SAMPLEDB=${DB2_TO_CREATE_SAMPLEDB:-false}
      - SAMPLEDB=${DB2_SAMPLEDB:-false}
      - IS_OSXFS=${DB2_IS_OSXFS:-true}
      - REPODB=${DB2_REPODB:-false}
      - HADR_ENABLED=${DB2_HADR_ENABLED:-false}
      - PERSISTENT_HOME=${DB2_PERSISTENT_HOME:-true}
      - ETCD_ENDPOINT=${DB2_ETCD_ENDPOINT:-}
      - ETCD_USERNAME=${DB2_ETCD_USERNAME:-}
      - ETCD_PASSWORD=${DB2_ETCD_PASSWORD:-}
    healthcheck:
      test: ["CMD", "/opt/ibm/db2/V11.5/bin/db2", "connect to duckdb"]
      interval: 10s
      timeout: 10s
      retries: 1000
      start_period: 40s
    volumes:
      - .data/db2/db:/database
