apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
  namespace: tabletop
  labels:
    type: local
spec:
  storageClassName: manual
  # storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvol/s3_pv"
