---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: tabletop
  labels:
    app: minio
data:
  MINIO_ROOT_USER: YWRtaW4K # base64(admin)
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQK # base64(password)
